version: '3.8'

services:
  backend:
    build: ./BEsocket
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
    volumes:
      - chat_data:/usr/src/app/data
    develop:
      watch:
        - action: rebuild
          path: ./BEsocket
          ignore:
            - node_modules/

  frontend:
    build: ./socketFE
    ports:
      - "8080:80"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./socketFE
          ignore:
            - node_modules/
            - dist/

volumes:
  chat_data:
